#!/bin/bash

# Google OAuth Setup - CLI Commands Script
# This script contains the commands needed to configure Google OAuth
# Run each command manually and follow the prompts

echo "================================================"
echo "Google OAuth Setup - Command Reference"
echo "================================================"
echo ""

echo "Step 1: Login to Supabase CLI"
echo "------------------------------"
echo "Command:"
echo "  npx supabase login"
echo ""
echo "What happens:"
echo "  - Opens browser for authentication"
echo "  - You'll authorize the CLI to access your Supabase account"
echo "  - Copy the verification code from browser back to terminal"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "Step 2: Link to Remote Supabase Project"
echo "----------------------------------------"
echo "Command:"
echo "  npx supabase link --project-ref izerdjlpdjnorczyxjva"
echo ""
echo "What happens:"
echo "  - Links local project to your remote Supabase project"
echo "  - May ask for database password (find in Supabase Dashboard → Settings → Database)"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "Step 3: Check Supabase Status"
echo "------------------------------"
echo "Command:"
echo "  npx supabase status"
echo ""
echo "What happens:"
echo "  - Shows your project connection status"
echo "  - Displays API URLs and keys"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "================================================"
echo "MANUAL STEPS REQUIRED (Can't be automated):"
echo "================================================"
echo ""

echo "Step 4: Create Google Cloud Project"
echo "------------------------------------"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Click 'Select a project' → 'New Project'"
echo "3. Name: TailorJob (or your choice)"
echo "4. Click 'Create'"
echo ""
read -p "Press Enter when done..."
echo ""

echo "Step 5: Enable Google+ API"
echo "-----------------------------------"
echo "1. Go to: APIs & Services → Library"
echo "2. Search for 'Google+ API'"
echo "3. Click it and click 'Enable'"
echo ""
read -p "Press Enter when done..."
echo ""

echo "Step 6: Configure OAuth Consent Screen"
echo "---------------------------------------"
echo "1. Go to: APIs & Services → OAuth consent screen"
echo "2. Choose: External (for public apps)"
echo "3. Fill in:"
echo "   - App name: TailorJob.ai"
echo "   - User support email: [your email]"
echo "   - Authorized domains: supabase.co"
echo "   - Developer contact: [your email]"
echo "4. Scopes: email, profile, openid (auto-selected)"
echo "5. Save and Continue through all steps"
echo ""
read -p "Press Enter when done..."
echo ""

echo "Step 7: Create OAuth Credentials"
echo "---------------------------------"
echo "1. Go to: APIs & Services → Credentials"
echo "2. Create Credentials → OAuth client ID"
echo "3. Type: Web application"
echo "4. Name: TailorJob Web Client"
echo "5. Authorized JavaScript origins:"
echo "   - http://localhost:5173"
echo "   - https://izerdjlpdjnorczyxjva.supabase.co"
echo "6. Authorized redirect URIs:"
echo "   - https://izerdjlpdjnorczyxjva.supabase.co/auth/v1/callback"
echo "7. Click Create"
echo ""
echo "⚠️  IMPORTANT: Save your credentials:"
echo "   Client ID: ___________________________________________"
echo "   Client Secret: ___________________________________________"
echo ""
read -p "Press Enter when you have saved your credentials..."
echo ""

echo "Step 8: Configure in Supabase Dashboard"
echo "----------------------------------------"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select project: izerdjlpdjnorczyxjva"
echo "3. Go to: Authentication → Providers"
echo "4. Find 'Google' and toggle it ON"
echo "5. Enter:"
echo "   - Client ID: [from Step 7]"
echo "   - Client Secret: [from Step 7]"
echo "6. Click 'Save'"
echo ""
read -p "Press Enter when done..."
echo ""

echo "Step 9: Test the OAuth Flow"
echo "----------------------------"
echo "1. Make sure dev server is running:"
echo "   npm run dev"
echo "2. Open: http://localhost:5173/signup"
echo "3. Click 'Sign up with Google'"
echo "4. Authorize with Google account"
echo "5. Should redirect to /dashboard"
echo ""
read -p "Press Enter when testing is complete..."
echo ""

echo "Step 10: Verify User in Supabase"
echo "---------------------------------"
echo "1. Go to Supabase Dashboard"
echo "2. Navigate to: Authentication → Users"
echo "3. Your user should appear with provider: 'google'"
echo ""
read -p "Press Enter when verified..."
echo ""

echo "================================================"
echo "✅ Setup Complete!"
echo "================================================"
echo ""
echo "Your app now supports free Google OAuth signup!"
echo ""
echo "Next steps:"
echo "  - Test login flow at /login"
echo "  - Test signup flow at /signup"
echo "  - Check user session management"
echo ""
echo "Documentation available in:"
echo "  - GOOGLE_OAUTH_SETUP.md (detailed guide)"
echo "  - GOOGLE_OAUTH_CHECKLIST.md (step-by-step)"
echo ""
echo "================================================"